import { useActor } from '../hooks/useActor';
import type { PersistedTranslation } from '../backend';

/**
 * Fetch all persisted translations from backend
 */
export async function fetchPersistedTranslations(actor: any): Promise<PersistedTranslation[]> {
  if (!actor) {
    return [];
  }

  try {
    const translations = await actor.getPersistedTranslations();
    return translations;
  } catch (error) {
    console.warn('Failed to fetch persisted translations:', error);
    return [];
  }
}

/**
 * Persist a new translation to backend
 */
export async function persistTranslation(
  actor: any,
  key: string,
  language: string,
  translatedText: string,
  englishSourceText: string
): Promise<void> {
  if (!actor) {
    return;
  }

  try {
    await actor.persistAutoGeneratedTranslation(key, language, translatedText, englishSourceText);
  } catch (error) {
    console.warn('Failed to persist translation:', error);
  }
}

/**
 * Normalize persisted translations into a lookup map
 */
export function normalizePersistedTranslations(
  translations: PersistedTranslation[]
): Map<string, Map<string, string>> {
  const normalized = new Map<string, Map<string, string>>();

  for (const translation of translations) {
    if (!normalized.has(translation.language)) {
      normalized.set(translation.language, new Map());
    }
    const langMap = normalized.get(translation.language)!;
    langMap.set(translation.englishSourceText, translation.translatedText);
  }

  return normalized;
}
